### PR TITLE
Fix error occuring when deleting categories/subcategories

### LINKED ISSUE #92: Categories and subcategories can't be deleted
**Describe the bug**
When deleting a category or subcategory with the DELETE request, it throws 500 internal server error

**To Reproduce**
1. Try to delete a category or subcategory using DELETE request
2. See error

**Expected behavior**
Subcategory and category get deleted. Orphans also should be removed

**Screenshots**
received_314879169916605

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Ubuntu 19.04
 - Postman

**Additional context**
N/A

### PR DESCRIPTION
**Pull request by Piumal1999**
## Purpose

The purpose of this PR is to fix #92 

## Goals

Fix internal server error occuring when deleting categories and subcategories

## Approach

Removed cascade types
Rewrite deleteSubCategory, deleteCategory methods on services

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation

## Related PRs
 
N/A

## Test environment
 
Ubuntu 19.04
Postman
OpenJDK 1.8

## Learning

https://www.baeldung.com/jpa-cascade-types
https://thorben-janssen.com/avoid-cascadetype-delete-many-assocations/

### CODE REVIEW

File: backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java [hunk 1]
```diff
@@ -152,12 +152,21 @@ public SubCategory updateSubCategory(long id, SubCategory subCategory)
...
             throw new ResourceNotFoundException(msg);
         }
+
+        List<Item> items = itemRepository.getAllBySubCategories(subCategory.get());
+        for (Item item: items) {
+            long itemId = item.getId();
+            if (item.getSubCategories().size()!=1){
+                itemRepository.getOne(itemId).getSubCategories().remove(subCategory.get());
+            }
+        }
```
Comment (YohanAvishke) [inline backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java:169]: Do the following logical change.

```suggestion
        SubCategory subCategoryObj = subCategory.get();
        List<Item> items = itemRepository.getAllBySubCategories(subCategoryObj);
        for (Item item: items) {
            item.getSubCategories().remove(subCategoryObj);
            subCategoryObj.getItems().clear();
        }
```

 It's better to move the for loop code into the SubCategory class by creating the following method
`void removeItems(List<Item> items)`

Comment (jayasanka-sack) [reply backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java:169]: I don't think moving DAO logics to the model is a good idea.

Comment (YohanAvishke) [reply backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java:169]: no, since this is logic is used to manipulate relationships it should be in the entity. 
Set methods are an example of that,
Eg: In SubCategory entity we have setItems method, etc.

Comment (Piumal1999) [reply backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java:169]: But with that, there will be isolated items. Is it ok to have isolated items?

Comment (YohanAvishke) [reply backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java:169]: There was a small bug in the suggestion, it's fixed now.
However @Piumal1999 there won't be isolated Items(Items without a Subcategory). This logic will remove the SubCategory from the Item if an Item has multiple SubCategories or else this will remove the item from the table.

BTW after some research, I found out that we should be able to achieve the proper delete functionality without manually looping. You can change the parent of the relationship to SubCategory, right now the parent is Item. Can you please try to test this as well.
Reference: https://stackoverflow.com/questions/1082095/how-to-remove-entity-with-manytomany-relationship-in-jpa-and-corresponding-join

Comment (Piumal1999) [reply backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java:169]: Ah i think it will work. I'll test that also

Comment (Piumal1999) [reply backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java:169]: I changed the parent of relationship by changing mapping. After changing that, the delete mapping works fine. But then, we can't set the SubCategories of an item from the item's side.
And when we are updating a subcategory, we will have to send the list of items also with the payload.

Comment (Piumal1999) [reply backend/src/main/java/org/sefglobal/core/academix/service/SubCategoryService.java]: Added the changes

File: backend/src/main/java/org/sefglobal/core/academix/model/SubCategory.java [hunk 2]
```diff
@@ -36,7 +36,7 @@
                orphanRemoval = true)
     private List<SubCategoryTranslation> translations = new ArrayList<>();
 
-    @ManyToOne(cascade = {CascadeType.MERGE})
+    @ManyToOne()
```
[the remark this answers is not in the document]
Comment (Piumal1999) [reply backend/src/main/java/org/sefglobal/core/academix/model/SubCategory.java]: Done

File: backend/src/main/java/org/sefglobal/core/academix/model/Item.java [hunk 3]
```diff
@@ -32,7 +32,7 @@
                orphanRemoval = true)
     private List<ItemTranslation> translations = new ArrayList<>();
 
-    @ManyToMany(cascade = {CascadeType.MERGE})
+    @ManyToMany()
```
[the remark this answers is not in the document]
Comment (Piumal1999) [reply backend/src/main/java/org/sefglobal/core/academix/model/Item.java]: Done
