### PR TITLE
Make AcademiX endpoints public

### LINKED ISSUE #46: 403 error occurred when accessing academix endpoints from the UI
**Describe the bug**
On AcademiX front end app requests on AcademiX data retrieval endpoints caught an error, logging 403 status code on the console. 

**To Reproduce**
1. Go to 'Academix frontend app'
2. Open dev tools

**Screenshots**
image

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Google Chrome

**Additional context**
This particular status code was sent by the API because the endpoints require an authorization. Making AcademiX endpoints public would do the trick.

### PR DESCRIPTION
**Pull request by Gravewalker666**
## Purpose
The purpose of this PR is to fix #46 

## Goals
To make the AcademiX endpoints public

## Approach
Inserted the academix to the config file in access level `permitAll()`

##  Checklist
- [x] This PR doesn't commit any keys, passwords, tokens, usernames, or other secrets.
- [x] I have read and understood the development best practices guidelines ( http://bit.ly/sef-best-practices )
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation

## Related PRs
N/A

## Test environment
Os: Ubuntu 19.04
Java Version: OpenJDK 1.8
IDE: IntelliJ IDEA

## Learning
- https://www.baeldung.com/spring-security-expressions

### CODE REVIEW

File: backend/src/main/java/org/sefglobal/core/config/SecurityConfig.java [hunk 1]
```diff
@@ -43,6 +43,7 @@ protected void configure(HttpSecurity http) throws Exception {
                 .csrf().disable()
                 .authorizeRequests()
                     .antMatchers("/link/*").permitAll()
+                    .antMatchers("/academix/*").permitAll()
```
Comment (jayasanka-sack) [inline backend/src/main/java/org/sefglobal/core/config/SecurityConfig.java:46]: If we do it this way, the add APIs also exposed to public.

Comment (Gravewalker666) [reply backend/src/main/java/org/sefglobal/core/config/SecurityConfig.java:46]: Let's name those APIs as `academix/admin` or something as we discussed.
